
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv() # reads the .env file

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales") # prints all the rows in the data table
    
    _global = []
    
    mf_struct = {
    	'cust' : [],
		'1_sum_quant': 0,
		'1_avg_quant': 0,
		'2_sum_quant': 0,
		'3_sum_quant': 0,
		'3_avg_quant': 0,
	}
    num_rows = 0 # keeps track of how many rows the mf_struct has
    
    for row in cur:
        if row['cust'] == "Wally" and row['quant'] == 193:
            _global.append(row)
    
    
    
    # convert all integer attributes to strings for tabulate
    for key in mf_struct.keys():
        if (isinstance(mf_struct.get(key), list)):
            continue
        mf_struct[key] = str(mf_struct.get(key))
    print(tabulate.tabulate(mf_struct, headers="keys", tablefmt="psql"))
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql") # returns data as a table

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    