
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

# Helper functions

def lookup(cur: dict, struct: dict, size: int, attrs: list) -> int: 
    """
    Search for a given "group by" attribute value(s) in mf_struct. 
    If the value(s) doesn't exist then return -1, else return the index for that row.

    :param cur: Current row in the mf_struct
    :param struct: The mf_struct
    :param size: Number of rows in the mf_struct
    :return: Either the index of the matching row in mf_struct or -1 if not found.
    """
    # iterate through each row in mf_struct
    for i in range(size):
        # iterate through each grouping attribute
        for attr in attrs:
            print(f"Cur: {cur[attr]} | MF-Struct: {struct.get(attr)[i]}")
            # mf_struct has the attribute value 
            if struct.get(attr)[i] == cur[attr]:
                print(f"Match! Cur: {cur[attr]} | MF-Struct: {struct.get(attr)[i]}")
                continue # check next attribute
            print("Unique attribute values found, leaving!")
            return -1 # mf_struct doesn't have the grouping attribute values in the given row 
    return i # mf_struct has all grouping attribute values in the given row


def query():
    load_dotenv() # reads the .env file

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales") # prints all the rows in the data table
    
    _global = []
    mf_struct = {
    	'cust' : ["Sam", "Dan", "Adora", "Catra"],
		'1_sum_quant': [96, 68, 26, 86],
		'1_avg_quant': [22, 57, 50, 99],
		'2_sum_quant': [10, 1, 94, 33],
		'3_sum_quant': [55, 54, 78, 56],
		'3_avg_quant': [10, 34, 56, 76],
	}
    
    num_rows = 1 # keeps track of how many rows the mf_struct has
    
    for row in cur:
        lookup(row, mf_struct, len(mf_struct["cust"]), ["cust"])
    
    
    
    print(tabulate.tabulate(mf_struct, headers="keys", tablefmt="psql")) # DEBUG
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql") # returns data as a table

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    